# Generated by Django 4.2.11 on 2024-03-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=150)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('food', 'Pet Food & water bowl'), ('Beds', 'Dog Beds'), ('kit', 'Pet Grooming Kits'), ('carrier', 'Pet Carrier'), ('Stainfree', 'Pet Stain & Order Removers'), ('Tr', 'Treats'), ('med', 'Pet Supplements & vitamins'), ('pro', 'Pet-Friendly Cleaning Products')], max_length=10)),
                ('product_image', models.ImageField(upload_to='pet_product')),
            ],
        ),
    ]
