# Generated by Django 4.2.11 on 2024-03-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=150)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('r', 'Rabits'), ('ck', 'Cats & Kitten'), ('dp', 'Dog & Puppies'), ('h', 'Hamsters, Rats'), ('f', 'Fish'), ('t', 'Turtle'), ('ho', 'Horse')], max_length=2)),
                ('product_image', models.ImageField(upload_to='pets')),
            ],
        ),
    ]
