# Generated by Django 4.1.1 on 2024-03-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0004_rename_product_image_pet_pet_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet_product',
            old_name='category',
            new_name='categoryy',
        ),
    ]
