# Generated by Django 4.1.1 on 2024-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetApp', '0007_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='area',
        ),
    ]
